### ISSUE TITLE
Update to 1.21.1

### ISSUE THREAD

**Issue by Nathack-dev** [joshi1999/Features-mod#5]
Hiii !
Can you update it to minicreft 1.21.1, plsss ! ❤️

**Comment by Nathack-dev** [comment]
UP !

**Comment by joshi1999** [comment]
I'll do that in the next few days ^^

**Comment by joshi1999** [comment]
Here you are ^^
https://github.com/joshi1999/Features-mod/releases/tag/1.3.6-1.21.1

If you find bugs, please don't hesitate to open a new issue :D
